name: Node.js CI

on:
  push:
    branches: [ "tests-snyk" ]
  pull_request:
    branches: [ "tests-snyk" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout juice-shop
      uses: actions/checkout@v4
      with:
        repository: juice-shop/juice-shop
        path: juice-shop

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd juice-shop
        npm install

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
