name: Node.js CI

on:
  push:
    branches: [ "tests-snyk" ]
  pull_request:
    branches: [ "tests-snyk" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install  # Isso deve gerar o package-lock.json

    - name: Ensure package-lock.json exists
      run: |
        if [ ! -f package-lock.json ]; then
          echo "Error: package-lock.json not found. Generating file.";
          npm install --package-lock-only;  # Gera o package-lock.json sem instalar as dependências
        fi

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
