name: Node.js CI

on:
  push:
    branches: [ "tests-snyk" ]
  pull_request:
    branches: [ "tests-snyk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout juice-shop
      uses: actions/checkout@v4
      with:
        repository: juice-shop/juice-shop
        path: juice-shop

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd juice-shop
        npm install || { echo "No dependencies found."; exit 0; }  # Tenta instalar, mas não falha se não houver dependências

    - name: Check for lock file
      run: |
        if [ ! -f juice-shop/package-lock.json ]; then
          echo "package-lock.json not found. Creating an empty file to proceed.";
          touch juice-shop/package-lock.json;  # Cria um arquivo vazio para evitar erros no Snyk
        fi

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
